// <auto-generated />
using MarketApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketApp.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221112142003_change some categories")]
    partial class changesomecategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-rc.2.22472.11");

            modelBuilder.Entity("MarketApp.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "24/365",
                            Url = "24/365"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Incredible Rubber Computer",
                            Url = "incredible rubber computer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SDD",
                            Url = "sdd"
                        },
                        new
                        {
                            Id = 4,
                            Name = "program",
                            Url = "program"
                        },
                        new
                        {
                            Id = 5,
                            Name = "embrace",
                            Url = "embrace"
                        });
                });

            modelBuilder.Entity("MarketApp.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "interactive applications Auto Loan Account",
                            ImageUrl = "https://picsum.photos/640/480/?image=875",
                            Price = 0.9665254004202140m,
                            Title = "Global"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Programmable",
                            ImageUrl = "https://picsum.photos/640/480/?image=166",
                            Price = 0.5998395713801130m,
                            Title = "Cambridgeshire"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "digital leverage",
                            ImageUrl = "https://picsum.photos/640/480/?image=608",
                            Price = 0.2066520775043770m,
                            Title = "Cotton"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Track pink Soft",
                            ImageUrl = "https://picsum.photos/640/480/?image=1020",
                            Price = 0.1704302667770820m,
                            Title = "Quality"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "reboot",
                            ImageUrl = "https://picsum.photos/640/480/?image=995",
                            Price = 0.9323436946798290m,
                            Title = "Credit Card Account"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            Description = "SAS",
                            ImageUrl = "https://picsum.photos/640/480/?image=385",
                            Price = 0.7618871372632180m,
                            Title = "alarm"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Ethiopian Birr",
                            ImageUrl = "https://picsum.photos/640/480/?image=656",
                            Price = 0.2042694985421450m,
                            Title = "Licensed"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "invoice Coordinator",
                            ImageUrl = "https://picsum.photos/640/480/?image=439",
                            Price = 0.5350905616749590m,
                            Title = "robust"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "uniform scale Turnpike",
                            ImageUrl = "https://picsum.photos/640/480/?image=773",
                            Price = 0.07311279992428580m,
                            Title = "Home, Baby & Toys"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Money Market Account Row",
                            ImageUrl = "https://picsum.photos/640/480/?image=1034",
                            Price = 0.6315360567423040m,
                            Title = "Open-source"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "Infrastructure Steel Chief",
                            ImageUrl = "https://picsum.photos/640/480/?image=28",
                            Price = 0.7054842136107530m,
                            Title = "invoice"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Ameliorated orchid",
                            ImageUrl = "https://picsum.photos/640/480/?image=972",
                            Price = 0.8662137102858880m,
                            Title = "Direct"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Description = "Baby Electronics, Grocery & Tools",
                            ImageUrl = "https://picsum.photos/640/480/?image=968",
                            Price = 0.4974352042437160m,
                            Title = "Beauty & Movies"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "Cambridgeshire",
                            ImageUrl = "https://picsum.photos/640/480/?image=747",
                            Price = 0.4045462349201020m,
                            Title = "black"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Description = "Cove scalable Bedfordshire",
                            ImageUrl = "https://picsum.photos/640/480/?image=603",
                            Price = 0.4822387860077920m,
                            Title = "Horizontal"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Cambridgeshire",
                            ImageUrl = "https://picsum.photos/640/480/?image=276",
                            Price = 0.7527020307704210m,
                            Title = "system"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Generic Tools Licensed Granite Bacon",
                            ImageUrl = "https://picsum.photos/640/480/?image=616",
                            Price = 0.8677455427636220m,
                            Title = "orchestration"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            Description = "Cambridgeshire Representative",
                            ImageUrl = "https://picsum.photos/640/480/?image=744",
                            Price = 0.7361021844648840m,
                            Title = "input"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "payment",
                            ImageUrl = "https://picsum.photos/640/480/?image=402",
                            Price = 0.719448499105090m,
                            Title = "Reverse-engineered"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Description = "Configuration Kyat",
                            ImageUrl = "https://picsum.photos/640/480/?image=1044",
                            Price = 0.7271752410077870m,
                            Title = "Handmade"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Description = "Personal Loan Account Designer JBOD",
                            ImageUrl = "https://picsum.photos/640/480/?image=641",
                            Price = 0.6313473659715280m,
                            Title = "Health"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            Description = "Guinea-Bissau Knoll",
                            ImageUrl = "https://picsum.photos/640/480/?image=769",
                            Price = 0.1678680511727240m,
                            Title = "Extended"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Description = "syndicate",
                            ImageUrl = "https://picsum.photos/640/480/?image=1036",
                            Price = 0.1181144171265930m,
                            Title = "panel"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            Description = "radical",
                            ImageUrl = "https://picsum.photos/640/480/?image=696",
                            Price = 0.4776208058467080m,
                            Title = "Florida"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Description = "Intelligent Steel Shirt",
                            ImageUrl = "https://picsum.photos/640/480/?image=994",
                            Price = 0.7658658587495650m,
                            Title = "back-end"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 4,
                            Description = "Gardens New Jersey Cote d'Ivoire",
                            ImageUrl = "https://picsum.photos/640/480/?image=509",
                            Price = 0.9776686403190110m,
                            Title = "Fresh"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            Description = "Practical Granite Soap Electronics white",
                            ImageUrl = "https://picsum.photos/640/480/?image=661",
                            Price = 0.2121430318518970m,
                            Title = "quantify"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Description = "Handmade Managed Reactive",
                            ImageUrl = "https://picsum.photos/640/480/?image=754",
                            Price = 0.8004457484381440m,
                            Title = "Accountability"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 4,
                            Description = "reboot",
                            ImageUrl = "https://picsum.photos/640/480/?image=365",
                            Price = 0.1709149040793780m,
                            Title = "convergence"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Description = "silver redundant",
                            ImageUrl = "https://picsum.photos/640/480/?image=874",
                            Price = 0.9497379751568720m,
                            Title = "static"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            Description = "Ergonomic",
                            ImageUrl = "https://picsum.photos/640/480/?image=346",
                            Price = 0.8176674406362370m,
                            Title = "open-source"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 1,
                            Description = "bluetooth",
                            ImageUrl = "https://picsum.photos/640/480/?image=691",
                            Price = 0.2851887922145460m,
                            Title = "seamless"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 5,
                            Description = "payment United Kingdom",
                            ImageUrl = "https://picsum.photos/640/480/?image=623",
                            Price = 0.4569169222562810m,
                            Title = "Integrated"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            Description = "Rwanda Franc",
                            ImageUrl = "https://picsum.photos/640/480/?image=261",
                            Price = 0.3666256451494950m,
                            Title = "redundant"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 2,
                            Description = "bluetooth",
                            ImageUrl = "https://picsum.photos/640/480/?image=1079",
                            Price = 0.8433783604247340m,
                            Title = "Directives"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            Description = "Dale Wisconsin",
                            ImageUrl = "https://picsum.photos/640/480/?image=329",
                            Price = 0.9202678820244820m,
                            Title = "Cross-platform"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 1,
                            Description = "Mongolia Vanuatu Credit Card Account",
                            ImageUrl = "https://picsum.photos/640/480/?image=1056",
                            Price = 0.5293601740619510m,
                            Title = "tan"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 5,
                            Description = "invoice mesh",
                            ImageUrl = "https://picsum.photos/640/480/?image=805",
                            Price = 0.8699871503074160m,
                            Title = "generate"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 1,
                            Description = "e-business Plains",
                            ImageUrl = "https://picsum.photos/640/480/?image=377",
                            Price = 0.6193895698608840m,
                            Title = "artificial intelligence"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Description = "Total THX",
                            ImageUrl = "https://picsum.photos/640/480/?image=1016",
                            Price = 0.3314499933059020m,
                            Title = "Pa'anga"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            Description = "Rial Omani",
                            ImageUrl = "https://picsum.photos/640/480/?image=1062",
                            Price = 0.3234830544320320m,
                            Title = "turquoise"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 3,
                            Description = "port",
                            ImageUrl = "https://picsum.photos/640/480/?image=236",
                            Price = 0.4905751627039460m,
                            Title = "Licensed"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            Description = "plug-and-play open architecture Representative",
                            ImageUrl = "https://picsum.photos/640/480/?image=535",
                            Price = 0.9072301561730030m,
                            Title = "Mongolia"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 4,
                            Description = "help-desk",
                            ImageUrl = "https://picsum.photos/640/480/?image=4",
                            Price = 0.05873491258814060m,
                            Title = "Field"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 3,
                            Description = "deposit South Dakota Park",
                            ImageUrl = "https://picsum.photos/640/480/?image=869",
                            Price = 0.001520963043350030m,
                            Title = "yellow"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 1,
                            Description = "Outdoors & Toys",
                            ImageUrl = "https://picsum.photos/640/480/?image=205",
                            Price = 0.2463675272298410m,
                            Title = "Manat"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 5,
                            Description = "firewall",
                            ImageUrl = "https://picsum.photos/640/480/?image=579",
                            Price = 0.1012104229970370m,
                            Title = "Rwanda Franc"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 1,
                            Description = "Colorado",
                            ImageUrl = "https://picsum.photos/640/480/?image=305",
                            Price = 0.00009524058360321780m,
                            Title = "Paradigm"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 1,
                            Description = "Hills",
                            ImageUrl = "https://picsum.photos/640/480/?image=731",
                            Price = 0.8039256089897430m,
                            Title = "world-class"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 4,
                            Description = "Berkshire",
                            ImageUrl = "https://picsum.photos/640/480/?image=838",
                            Price = 0.8218550105689060m,
                            Title = "Intelligent"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 4,
                            Description = "orchid",
                            ImageUrl = "https://picsum.photos/640/480/?image=432",
                            Price = 0.5758622227092470m,
                            Title = "Avon"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 1,
                            Description = "whiteboard",
                            ImageUrl = "https://picsum.photos/640/480/?image=1078",
                            Price = 0.08073535715109340m,
                            Title = "backing up"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 2,
                            Description = "USB",
                            ImageUrl = "https://picsum.photos/640/480/?image=120",
                            Price = 0.5427597480253470m,
                            Title = "Jordan"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 5,
                            Description = "Garden, Computers & Tools",
                            ImageUrl = "https://picsum.photos/640/480/?image=869",
                            Price = 0.1433941261244020m,
                            Title = "North Carolina"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 4,
                            Description = "Practical Frozen Chicken syndicate",
                            ImageUrl = "https://picsum.photos/640/480/?image=803",
                            Price = 0.5765299791156970m,
                            Title = "National"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 4,
                            Description = "neural Mills bandwidth",
                            ImageUrl = "https://picsum.photos/640/480/?image=798",
                            Price = 0.2812311058504940m,
                            Title = "Metal"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 3,
                            Description = "Buckinghamshire",
                            ImageUrl = "https://picsum.photos/640/480/?image=729",
                            Price = 0.1293810691663150m,
                            Title = "Pre-emptive"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 5,
                            Description = "Pike",
                            ImageUrl = "https://picsum.photos/640/480/?image=1072",
                            Price = 0.4605029052410740m,
                            Title = "vertical"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 2,
                            Description = "Generic Quality Granite",
                            ImageUrl = "https://picsum.photos/640/480/?image=553",
                            Price = 0.027437187967260m,
                            Title = "Kids, Kids & Baby"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 1,
                            Description = "Sleek Guyana Dollar Cambridgeshire",
                            ImageUrl = "https://picsum.photos/640/480/?image=698",
                            Price = 0.6515326675635890m,
                            Title = "Handcrafted Concrete Pants"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 1,
                            Description = "Global",
                            ImageUrl = "https://picsum.photos/640/480/?image=7",
                            Price = 0.9485923002468330m,
                            Title = "Computers, Automotive & Shoes"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 5,
                            Description = "Web",
                            ImageUrl = "https://picsum.photos/640/480/?image=680",
                            Price = 0.2599816890302560m,
                            Title = "payment"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 2,
                            Description = "blue Product Personal Loan Account",
                            ImageUrl = "https://picsum.photos/640/480/?image=1019",
                            Price = 0.8163048099126160m,
                            Title = "Generic Soft Hat"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 3,
                            Description = "payment",
                            ImageUrl = "https://picsum.photos/640/480/?image=976",
                            Price = 0.8737949362133540m,
                            Title = "User-centric"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 2,
                            Description = "Wisconsin iterate",
                            ImageUrl = "https://picsum.photos/640/480/?image=736",
                            Price = 0.04688264599416090m,
                            Title = "Licensed Plastic Cheese"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 1,
                            Description = "neural-net Point gold",
                            ImageUrl = "https://picsum.photos/640/480/?image=810",
                            Price = 0.379897883069590m,
                            Title = "Engineer"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 1,
                            Description = "orange",
                            ImageUrl = "https://picsum.photos/640/480/?image=763",
                            Price = 0.5776461745417620m,
                            Title = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 2,
                            Description = "Beauty, Electronics & Industrial",
                            ImageUrl = "https://picsum.photos/640/480/?image=828",
                            Price = 0.9009229768686650m,
                            Title = "navigate"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 2,
                            Description = "Frozen",
                            ImageUrl = "https://picsum.photos/640/480/?image=697",
                            Price = 0.8018986595473090m,
                            Title = "experiences"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 4,
                            Description = "Industrial, Games & Shoes",
                            ImageUrl = "https://picsum.photos/640/480/?image=42",
                            Price = 0.6781155987445040m,
                            Title = "white"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 1,
                            Description = "Togo Directives HDD",
                            ImageUrl = "https://picsum.photos/640/480/?image=895",
                            Price = 0.03514794371906370m,
                            Title = "Handmade Soft Gloves"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 4,
                            Description = "Personal Loan Account demand-driven Program",
                            ImageUrl = "https://picsum.photos/640/480/?image=244",
                            Price = 0.5093357091095230m,
                            Title = "help-desk"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 4,
                            Description = "Divide",
                            ImageUrl = "https://picsum.photos/640/480/?image=874",
                            Price = 0.5283742191852630m,
                            Title = "SMS"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 4,
                            Description = "Liaison",
                            ImageUrl = "https://picsum.photos/640/480/?image=60",
                            Price = 0.4228703689943570m,
                            Title = "Switchable"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 5,
                            Description = "systemic",
                            ImageUrl = "https://picsum.photos/640/480/?image=767",
                            Price = 0.3189810595778920m,
                            Title = "Music, Music & Garden"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 3,
                            Description = "Wisconsin Rustic Plastic Car interface",
                            ImageUrl = "https://picsum.photos/640/480/?image=905",
                            Price = 0.3722831521505170m,
                            Title = "quantify"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 3,
                            Description = "Denmark",
                            ImageUrl = "https://picsum.photos/640/480/?image=266",
                            Price = 0.6719283296039910m,
                            Title = "monitor"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 3,
                            Description = "Integration Clothing",
                            ImageUrl = "https://picsum.photos/640/480/?image=974",
                            Price = 0.5801060170722280m,
                            Title = "eyeballs"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 5,
                            Description = "Guadeloupe",
                            ImageUrl = "https://picsum.photos/640/480/?image=876",
                            Price = 0.4159348910414540m,
                            Title = "even-keeled"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 3,
                            Description = "Borders Practical",
                            ImageUrl = "https://picsum.photos/640/480/?image=1032",
                            Price = 0.02725615332161360m,
                            Title = "Auto Loan Account"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 2,
                            Description = "multimedia bus payment",
                            ImageUrl = "https://picsum.photos/640/480/?image=629",
                            Price = 0.6889164400257790m,
                            Title = "Dynamic"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 1,
                            Description = "black",
                            ImageUrl = "https://picsum.photos/640/480/?image=393",
                            Price = 0.9294101013455070m,
                            Title = "Congolese Franc"
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 2,
                            Description = "Orchestrator parsing",
                            ImageUrl = "https://picsum.photos/640/480/?image=67",
                            Price = 0.4312914363752510m,
                            Title = "Road"
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 3,
                            Description = "silver Iowa Operations",
                            ImageUrl = "https://picsum.photos/640/480/?image=605",
                            Price = 0.5703609390252840m,
                            Title = "rich"
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 4,
                            Description = "bus",
                            ImageUrl = "https://picsum.photos/640/480/?image=931",
                            Price = 0.6303524657335280m,
                            Title = "wireless"
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 1,
                            Description = "Soft e-business",
                            ImageUrl = "https://picsum.photos/640/480/?image=730",
                            Price = 0.1788298839567580m,
                            Title = "Checking Account"
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 3,
                            Description = "Grocery & Movies",
                            ImageUrl = "https://picsum.photos/640/480/?image=320",
                            Price = 0.5815989742301970m,
                            Title = "Planner"
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 2,
                            Description = "Personal Loan Account connect interfaces",
                            ImageUrl = "https://picsum.photos/640/480/?image=105",
                            Price = 0.6738173458761850m,
                            Title = "Frozen"
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 2,
                            Description = "grey compressing Practical",
                            ImageUrl = "https://picsum.photos/640/480/?image=565",
                            Price = 0.7381102516469040m,
                            Title = "New Mexico"
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 2,
                            Description = "Clothing Utah haptic",
                            ImageUrl = "https://picsum.photos/640/480/?image=696",
                            Price = 0.9308805687643590m,
                            Title = "B2B"
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 1,
                            Description = "neural Concrete Robust",
                            ImageUrl = "https://picsum.photos/640/480/?image=59",
                            Price = 0.8801856640808740m,
                            Title = "Arizona"
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 1,
                            Description = "Generic Soft Shirt FTP",
                            ImageUrl = "https://picsum.photos/640/480/?image=814",
                            Price = 0.8874386208178440m,
                            Title = "experiences"
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 1,
                            Description = "Ergonomic",
                            ImageUrl = "https://picsum.photos/640/480/?image=222",
                            Price = 0.6052081155467880m,
                            Title = "COM"
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 4,
                            Description = "lime",
                            ImageUrl = "https://picsum.photos/640/480/?image=166",
                            Price = 0.2171810201230360m,
                            Title = "contingency"
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 5,
                            Description = "bus",
                            ImageUrl = "https://picsum.photos/640/480/?image=662",
                            Price = 0.8773015770917330m,
                            Title = "reinvent"
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 2,
                            Description = "program",
                            ImageUrl = "https://picsum.photos/640/480/?image=42",
                            Price = 0.2812472524958230m,
                            Title = "global"
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 2,
                            Description = "Gibraltar Pound",
                            ImageUrl = "https://picsum.photos/640/480/?image=683",
                            Price = 0.54349424473780m,
                            Title = "Malta"
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 5,
                            Description = "vertical",
                            ImageUrl = "https://picsum.photos/640/480/?image=928",
                            Price = 0.4233552970760010m,
                            Title = "Devolved"
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 3,
                            Description = "Cordoba Oro Forge European Unit of Account 9(E.U.A.-9)",
                            ImageUrl = "https://picsum.photos/640/480/?image=918",
                            Price = 0.1704332474434940m,
                            Title = "input"
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 3,
                            Description = "El Salvador Colon",
                            ImageUrl = "https://picsum.photos/640/480/?image=464",
                            Price = 0.8490165293326960m,
                            Title = "capacitor"
                        });
                });

            modelBuilder.Entity("MarketApp.Shared.Product", b =>
                {
                    b.HasOne("MarketApp.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
