// <auto-generated />
using MarketApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketApp.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221110140747_init fake data")]
    partial class initfakedata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-rc.2.22472.11");

            modelBuilder.Entity("MarketApp.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "program",
                            Url = "program"
                        },
                        new
                        {
                            Id = 2,
                            Name = "lavender",
                            Url = "lavender"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Savings Account",
                            Url = "savings account"
                        },
                        new
                        {
                            Id = 4,
                            Name = "cutting-edge",
                            Url = "cutting-edge"
                        },
                        new
                        {
                            Id = 5,
                            Name = "TCP",
                            Url = "tcp"
                        },
                        new
                        {
                            Id = 6,
                            Name = "time-frame",
                            Url = "time-frame"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Corporate",
                            Url = "corporate"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ghana",
                            Url = "ghana"
                        },
                        new
                        {
                            Id = 9,
                            Name = "South Carolina",
                            Url = "south carolina"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Enhanced",
                            Url = "enhanced"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Spurs",
                            Url = "spurs"
                        },
                        new
                        {
                            Id = 12,
                            Name = "THX",
                            Url = "thx"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Landing",
                            Url = "landing"
                        },
                        new
                        {
                            Id = 14,
                            Name = "protocol",
                            Url = "protocol"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Response",
                            Url = "response"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Rubber",
                            Url = "rubber"
                        },
                        new
                        {
                            Id = 17,
                            Name = "salmon",
                            Url = "salmon"
                        },
                        new
                        {
                            Id = 18,
                            Name = "generate",
                            Url = "generate"
                        },
                        new
                        {
                            Id = 19,
                            Name = "strategic",
                            Url = "strategic"
                        },
                        new
                        {
                            Id = 20,
                            Name = "relationships",
                            Url = "relationships"
                        });
                });

            modelBuilder.Entity("MarketApp.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 12,
                            Description = "red Auto Loan Account navigating",
                            ImageUrl = "https://picsum.photos/640/480/?image=1069",
                            Price = 0.4591908585402250m,
                            Title = "models"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 11,
                            Description = "Steel Alaska invoice",
                            ImageUrl = "https://picsum.photos/640/480/?image=539",
                            Price = 0.8782998746253810m,
                            Title = "Direct"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "magenta New Mexico Drive",
                            ImageUrl = "https://picsum.photos/640/480/?image=254",
                            Price = 0.5919881096541780m,
                            Title = "enterprise"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 12,
                            Description = "synthesize 4th generation",
                            ImageUrl = "https://picsum.photos/640/480/?image=408",
                            Price = 0.8289136459954160m,
                            Title = "Spur"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Turkish Lira Soft Burkina Faso",
                            ImageUrl = "https://picsum.photos/640/480/?image=301",
                            Price = 0.4042950562715520m,
                            Title = "Guinea"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 19,
                            Description = "Facilitator",
                            ImageUrl = "https://picsum.photos/640/480/?image=46",
                            Price = 0.1333902662784290m,
                            Title = "East Caribbean Dollar"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Future Auto Loan Account",
                            ImageUrl = "https://picsum.photos/640/480/?image=954",
                            Price = 0.2902385712511810m,
                            Title = "Cambridgeshire"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 19,
                            Description = "AI Chad Handcrafted",
                            ImageUrl = "https://picsum.photos/640/480/?image=1072",
                            Price = 0.1525986530209030m,
                            Title = "Dynamic"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 7,
                            Description = "enhance",
                            ImageUrl = "https://picsum.photos/640/480/?image=493",
                            Price = 0.8849403244758140m,
                            Title = "payment"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 7,
                            Description = "generate Cotton Configuration",
                            ImageUrl = "https://picsum.photos/640/480/?image=219",
                            Price = 0.7649123579793960m,
                            Title = "Computers, Tools & Beauty"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 17,
                            Description = "payment",
                            ImageUrl = "https://picsum.photos/640/480/?image=390",
                            Price = 0.02537261229502430m,
                            Title = "Malagasy Ariary"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 16,
                            Description = "CSS Personal Loan Account exploit",
                            ImageUrl = "https://picsum.photos/640/480/?image=207",
                            Price = 0.2386488541910810m,
                            Title = "Unbranded Soft Towels"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "generating California",
                            ImageUrl = "https://picsum.photos/640/480/?image=724",
                            Price = 0.6849361969050630m,
                            Title = "e-commerce"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 17,
                            Description = "parse Rwanda firmware",
                            ImageUrl = "https://picsum.photos/640/480/?image=821",
                            Price = 0.7099702144065030m,
                            Title = "Vision-oriented"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Description = "fuchsia deposit",
                            ImageUrl = "https://picsum.photos/640/480/?image=278",
                            Price = 0.9360734384961360m,
                            Title = "bandwidth"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 20,
                            Description = "transparent Wall",
                            ImageUrl = "https://picsum.photos/640/480/?image=846",
                            Price = 0.6339809942639940m,
                            Title = "Utah"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 20,
                            Description = "connect Well",
                            ImageUrl = "https://picsum.photos/640/480/?image=477",
                            Price = 0.3152268917113990m,
                            Title = "Handmade Cotton Pants"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Description = "HTTP Islands",
                            ImageUrl = "https://picsum.photos/640/480/?image=3",
                            Price = 0.8845169364849360m,
                            Title = "Libyan Dinar"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 8,
                            Description = "IB Books Israel",
                            ImageUrl = "https://picsum.photos/640/480/?image=590",
                            Price = 0.2966574477050680m,
                            Title = "compress"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 11,
                            Description = "Money Market Account redundant website",
                            ImageUrl = "https://picsum.photos/640/480/?image=223",
                            Price = 0.5732423393145120m,
                            Title = "enhance"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            Description = "Junctions North Carolina client-server",
                            ImageUrl = "https://picsum.photos/640/480/?image=634",
                            Price = 0.3384615429942750m,
                            Title = "deposit"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 10,
                            Description = "Drive gold",
                            ImageUrl = "https://picsum.photos/640/480/?image=719",
                            Price = 0.2464911109572780m,
                            Title = "B2B"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 19,
                            Description = "South Georgia and the South Sandwich Islands Kina",
                            ImageUrl = "https://picsum.photos/640/480/?image=528",
                            Price = 0.6304824590762030m,
                            Title = "budgetary management"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 6,
                            Description = "wireless Concrete Metrics",
                            ImageUrl = "https://picsum.photos/640/480/?image=1057",
                            Price = 0.5825068766790850m,
                            Title = "Metrics"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Description = "Metal back up",
                            ImageUrl = "https://picsum.photos/640/480/?image=533",
                            Price = 0.6705873037909120m,
                            Title = "disintermediate"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 7,
                            Description = "Producer Drives Gold",
                            ImageUrl = "https://picsum.photos/640/480/?image=662",
                            Price = 0.1589859845573280m,
                            Title = "schemas"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 20,
                            Description = "synergistic Belgium",
                            ImageUrl = "https://picsum.photos/640/480/?image=203",
                            Price = 0.6500834703009970m,
                            Title = "Buckinghamshire"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 13,
                            Description = "Dominican Republic withdrawal channels",
                            ImageUrl = "https://picsum.photos/640/480/?image=903",
                            Price = 0.1486947705271360m,
                            Title = "Refined"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 8,
                            Description = "Point programming",
                            ImageUrl = "https://picsum.photos/640/480/?image=395",
                            Price = 0.03997715579240450m,
                            Title = "invoice"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 19,
                            Description = "payment Operations Distributed",
                            ImageUrl = "https://picsum.photos/640/480/?image=120",
                            Price = 0.4202340868626720m,
                            Title = "navigate"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 19,
                            Description = "models",
                            ImageUrl = "https://picsum.photos/640/480/?image=1003",
                            Price = 0.6670530195975460m,
                            Title = "copying"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 19,
                            Description = "Digitized",
                            ImageUrl = "https://picsum.photos/640/480/?image=1076",
                            Price = 0.9077327213158320m,
                            Title = "backing up"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 12,
                            Description = "Direct",
                            ImageUrl = "https://picsum.photos/640/480/?image=466",
                            Price = 0.6360598807140320m,
                            Title = "Books, Kids & Kids"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 14,
                            Description = "quantify payment",
                            ImageUrl = "https://picsum.photos/640/480/?image=9",
                            Price = 0.4237339156949170m,
                            Title = "Unbranded Fresh Chair"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 18,
                            Description = "deliver Licensed Steel Ball Park",
                            ImageUrl = "https://picsum.photos/640/480/?image=879",
                            Price = 0.8676752836915070m,
                            Title = "revolutionary"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 18,
                            Description = "Product experiences",
                            ImageUrl = "https://picsum.photos/640/480/?image=888",
                            Price = 0.5663098765891510m,
                            Title = "Usability"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 9,
                            Description = "Indian Rupee magenta",
                            ImageUrl = "https://picsum.photos/640/480/?image=151",
                            Price = 0.6643886943180480m,
                            Title = "withdrawal"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 17,
                            Description = "Prairie sensor action-items",
                            ImageUrl = "https://picsum.photos/640/480/?image=395",
                            Price = 0.7787062448121420m,
                            Title = "Generic Soft Bacon"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 5,
                            Description = "Shoal Cambridgeshire",
                            ImageUrl = "https://picsum.photos/640/480/?image=69",
                            Price = 0.3841720728303790m,
                            Title = "asynchronous"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 3,
                            Description = "Metal",
                            ImageUrl = "https://picsum.photos/640/480/?image=109",
                            Price = 0.7061102481879710m,
                            Title = "Steel"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 10,
                            Description = "red",
                            ImageUrl = "https://picsum.photos/640/480/?image=976",
                            Price = 0.3990801438484810m,
                            Title = "withdrawal"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 9,
                            Description = "neural Tasty Rubber Towels PNG",
                            ImageUrl = "https://picsum.photos/640/480/?image=1030",
                            Price = 0.7401998550192690m,
                            Title = "cross-platform"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            Description = "Awesome Steel Tuna Global",
                            ImageUrl = "https://picsum.photos/640/480/?image=285",
                            Price = 0.5133939336126170m,
                            Title = "responsive"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 19,
                            Description = "Digitized",
                            ImageUrl = "https://picsum.photos/640/480/?image=25",
                            Price = 0.3977843006304820m,
                            Title = "Harbor"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 8,
                            Description = "overriding Optimization Engineer",
                            ImageUrl = "https://picsum.photos/640/480/?image=497",
                            Price = 0.4904414226121620m,
                            Title = "indigo"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 15,
                            Description = "strategy Rustic Wooden Soap transmitting",
                            ImageUrl = "https://picsum.photos/640/480/?image=798",
                            Price = 0.979224795507190m,
                            Title = "Generic Metal Fish"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 5,
                            Description = "Awesome Cotton Chicken Cook Islands",
                            ImageUrl = "https://picsum.photos/640/480/?image=805",
                            Price = 0.9235797972878820m,
                            Title = "Specialist"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 17,
                            Description = "Small Concrete Bike Buckinghamshire",
                            ImageUrl = "https://picsum.photos/640/480/?image=319",
                            Price = 0.2370368841653140m,
                            Title = "collaborative"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 19,
                            Description = "Versatile convergence",
                            ImageUrl = "https://picsum.photos/640/480/?image=805",
                            Price = 0.2523714213667230m,
                            Title = "harness"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 1,
                            Description = "Movies & Shoes",
                            ImageUrl = "https://picsum.photos/640/480/?image=164",
                            Price = 0.4732622577219790m,
                            Title = "West Virginia"
                        });
                });

            modelBuilder.Entity("MarketApp.Shared.Product", b =>
                {
                    b.HasOne("MarketApp.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
