// <auto-generated />
using MarketApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketApp.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-rc.2.22472.11");

            modelBuilder.Entity("MarketApp.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "PDDDD",
                            ImageUrl = "https://chaoskey.oschina.io/notes/images/0109.jpg",
                            Price = 9.99m,
                            Title = "A"
                        },
                        new
                        {
                            Id = 2,
                            Description = "PDDDD",
                            ImageUrl = "https://chaoskey.oschina.io/notes/images/0109.jpg",
                            Price = 19.99m,
                            Title = "B"
                        },
                        new
                        {
                            Id = 3,
                            Description = "PDDDD",
                            ImageUrl = "https://chaoskey.oschina.io/notes/images/0109.jpg",
                            Price = 29.99m,
                            Title = "C"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
