// <auto-generated />
using MarketApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketApp.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-rc.2.22472.11");

            modelBuilder.Entity("MarketApp.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Centralized",
                            Url = "centralized"
                        },
                        new
                        {
                            Id = 2,
                            Name = "synthesize",
                            Url = "synthesize"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Product",
                            Url = "product"
                        },
                        new
                        {
                            Id = 4,
                            Name = "neural",
                            Url = "neural"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ports",
                            Url = "ports"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ergonomic Soft Chair",
                            Url = "ergonomic soft chair"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Games & Toys",
                            Url = "games & toys"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Louisiana",
                            Url = "louisiana"
                        },
                        new
                        {
                            Id = 9,
                            Name = "embrace",
                            Url = "embrace"
                        },
                        new
                        {
                            Id = 10,
                            Name = "quantifying",
                            Url = "quantifying"
                        },
                        new
                        {
                            Id = 11,
                            Name = "software",
                            Url = "software"
                        },
                        new
                        {
                            Id = 12,
                            Name = "green",
                            Url = "green"
                        },
                        new
                        {
                            Id = 13,
                            Name = "transition",
                            Url = "transition"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Supervisor",
                            Url = "supervisor"
                        },
                        new
                        {
                            Id = 15,
                            Name = "integrated",
                            Url = "integrated"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Rubber",
                            Url = "rubber"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Avon",
                            Url = "avon"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Creek",
                            Url = "creek"
                        },
                        new
                        {
                            Id = 19,
                            Name = "withdrawal",
                            Url = "withdrawal"
                        },
                        new
                        {
                            Id = 20,
                            Name = "proactive",
                            Url = "proactive"
                        });
                });

            modelBuilder.Entity("MarketApp.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            Description = "Movies, Automotive & Automotive",
                            ImageUrl = "https://picsum.photos/640/480/?image=982",
                            Price = 0.09704865928557020m,
                            Title = "auxiliary"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 10,
                            Description = "green",
                            ImageUrl = "https://picsum.photos/640/480/?image=792",
                            Price = 0.2188268138818930m,
                            Title = "Analyst"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 11,
                            Description = "Specialist",
                            ImageUrl = "https://picsum.photos/640/480/?image=907",
                            Price = 0.5924540708555420m,
                            Title = "index"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 14,
                            Description = "SAS",
                            ImageUrl = "https://picsum.photos/640/480/?image=68",
                            Price = 0.2712196068124340m,
                            Title = "SMS"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 19,
                            Description = "Savings Account synergy Home Loan Account",
                            ImageUrl = "https://picsum.photos/640/480/?image=79",
                            Price = 0.5431039372329590m,
                            Title = "withdrawal"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 7,
                            Description = "Handmade Cotton Towels Granite",
                            ImageUrl = "https://picsum.photos/640/480/?image=671",
                            Price = 0.08684005129961270m,
                            Title = "Ramp"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 17,
                            Description = "deposit compressing",
                            ImageUrl = "https://picsum.photos/640/480/?image=333",
                            Price = 0.7445156121727590m,
                            Title = "Springs"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "New Caledonia backing up",
                            ImageUrl = "https://picsum.photos/640/480/?image=409",
                            Price = 0.6916672732764870m,
                            Title = "Money Market Account"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 18,
                            Description = "Cove pixel",
                            ImageUrl = "https://picsum.photos/640/480/?image=973",
                            Price = 0.5661251806881360m,
                            Title = "Indiana"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "B2C Assistant Investor",
                            ImageUrl = "https://picsum.photos/640/480/?image=139",
                            Price = 0.644513148148950m,
                            Title = "Small Cotton Car"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Berkshire Creek generate",
                            ImageUrl = "https://picsum.photos/640/480/?image=476",
                            Price = 0.0881751192762140m,
                            Title = "ivory"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 7,
                            Description = "Parks withdrawal",
                            ImageUrl = "https://picsum.photos/640/480/?image=631",
                            Price = 0.6773562321483620m,
                            Title = "Key"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 9,
                            Description = "indexing",
                            ImageUrl = "https://picsum.photos/640/480/?image=459",
                            Price = 0.3430671906592360m,
                            Title = "Cape"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 18,
                            Description = "driver hybrid invoice",
                            ImageUrl = "https://picsum.photos/640/480/?image=532",
                            Price = 0.4596908186888730m,
                            Title = "feed"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "auxiliary",
                            ImageUrl = "https://picsum.photos/640/480/?image=374",
                            Price = 0.7759023588502580m,
                            Title = "system"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "Granite",
                            ImageUrl = "https://picsum.photos/640/480/?image=385",
                            Price = 0.1175122404938910m,
                            Title = "overriding"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 16,
                            Description = "Montana",
                            ImageUrl = "https://picsum.photos/640/480/?image=545",
                            Price = 0.881574733235660m,
                            Title = "redundant"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 7,
                            Description = "Plastic XML",
                            ImageUrl = "https://picsum.photos/640/480/?image=831",
                            Price = 0.06158321909415790m,
                            Title = "Executive"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 6,
                            Description = "FTP",
                            ImageUrl = "https://picsum.photos/640/480/?image=865",
                            Price = 0.9023295801786140m,
                            Title = "Program"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 11,
                            Description = "Rustic Granite Gloves Consultant",
                            ImageUrl = "https://picsum.photos/640/480/?image=1044",
                            Price = 0.9884119145598320m,
                            Title = "District"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 15,
                            Description = "scalable Small Concrete Pizza Baby, Automotive & Jewelery",
                            ImageUrl = "https://picsum.photos/640/480/?image=864",
                            Price = 0.2936221258781160m,
                            Title = "compressing"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 8,
                            Description = "port demand-driven",
                            ImageUrl = "https://picsum.photos/640/480/?image=990",
                            Price = 0.8609509219870420m,
                            Title = "Won"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Description = "UIC-Franc bluetooth",
                            ImageUrl = "https://picsum.photos/640/480/?image=905",
                            Price = 0.6597034041625130m,
                            Title = "maroon"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 19,
                            Description = "Mountains Ergonomic Steel Bacon",
                            ImageUrl = "https://picsum.photos/640/480/?image=310",
                            Price = 0.09860280042542440m,
                            Title = "Grocery"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 10,
                            Description = "Orchestrator software",
                            ImageUrl = "https://picsum.photos/640/480/?image=1",
                            Price = 0.9340070629927330m,
                            Title = "haptic"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 4,
                            Description = "Handcrafted Cotton Pants Savings Account hard drive",
                            ImageUrl = "https://picsum.photos/640/480/?image=592",
                            Price = 0.198294344478610m,
                            Title = "orange"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            Description = "Syrian Pound",
                            ImageUrl = "https://picsum.photos/640/480/?image=367",
                            Price = 0.7179529161572640m,
                            Title = "Tasty Plastic Pizza"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 12,
                            Description = "compress",
                            ImageUrl = "https://picsum.photos/640/480/?image=396",
                            Price = 0.7913470619511020m,
                            Title = "Corporate"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 17,
                            Description = "1080p",
                            ImageUrl = "https://picsum.photos/640/480/?image=179",
                            Price = 0.8003013878387470m,
                            Title = "Ohio"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 9,
                            Description = "withdrawal hard drive Fundamental",
                            ImageUrl = "https://picsum.photos/640/480/?image=214",
                            Price = 0.1595396952323310m,
                            Title = "Small Rubber Shirt"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 14,
                            Description = "bypassing orange",
                            ImageUrl = "https://picsum.photos/640/480/?image=714",
                            Price = 0.5168651139965380m,
                            Title = "Security"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            Description = "productize",
                            ImageUrl = "https://picsum.photos/640/480/?image=657",
                            Price = 0.02127036614983960m,
                            Title = "Isle"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 14,
                            Description = "Fantastic Florida",
                            ImageUrl = "https://picsum.photos/640/480/?image=96",
                            Price = 0.06263015279787050m,
                            Title = "Steel"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 16,
                            Description = "users Refined Rubber Table TCP",
                            ImageUrl = "https://picsum.photos/640/480/?image=977",
                            Price = 0.1391426458476170m,
                            Title = "transmitting"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 16,
                            Description = "Cross-group utilisation withdrawal",
                            ImageUrl = "https://picsum.photos/640/480/?image=256",
                            Price = 0.3937756376219510m,
                            Title = "SCSI"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 11,
                            Description = "Metal",
                            ImageUrl = "https://picsum.photos/640/480/?image=353",
                            Price = 0.5133066549712820m,
                            Title = "turquoise"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 5,
                            Description = "database Accounts",
                            ImageUrl = "https://picsum.photos/640/480/?image=317",
                            Price = 0.1285496790549730m,
                            Title = "seamless"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 15,
                            Description = "Metal Ergonomic Fresh Table Ranch",
                            ImageUrl = "https://picsum.photos/640/480/?image=92",
                            Price = 0.4198633710966570m,
                            Title = "array"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 19,
                            Description = "Generic payment Avon",
                            ImageUrl = "https://picsum.photos/640/480/?image=899",
                            Price = 0.01920899100289240m,
                            Title = "proactive"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 5,
                            Description = "Islands Row",
                            ImageUrl = "https://picsum.photos/640/480/?image=159",
                            Price = 0.09045887276729070m,
                            Title = "alarm"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 20,
                            Description = "B2C Checking Account monitor",
                            ImageUrl = "https://picsum.photos/640/480/?image=953",
                            Price = 0.1530777865361980m,
                            Title = "experiences"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            Description = "Lake Savings Account Corporate",
                            ImageUrl = "https://picsum.photos/640/480/?image=255",
                            Price = 0.1204186049886620m,
                            Title = "Fresh"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 16,
                            Description = "Course",
                            ImageUrl = "https://picsum.photos/640/480/?image=355",
                            Price = 0.6511596181758390m,
                            Title = "channels"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 9,
                            Description = "override maximize Money Market Account",
                            ImageUrl = "https://picsum.photos/640/480/?image=325",
                            Price = 0.4224335344083790m,
                            Title = "Union"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 8,
                            Description = "Borders",
                            ImageUrl = "https://picsum.photos/640/480/?image=991",
                            Price = 0.8866676913226770m,
                            Title = "Clothing, Shoes & Baby"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 13,
                            Description = "system",
                            ImageUrl = "https://picsum.photos/640/480/?image=1076",
                            Price = 0.340955988103510m,
                            Title = "Handmade Steel Shirt"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 2,
                            Description = "XML Communications override",
                            ImageUrl = "https://picsum.photos/640/480/?image=909",
                            Price = 0.9913504379314130m,
                            Title = "SSL"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 8,
                            Description = "Toys, Toys & Music",
                            ImageUrl = "https://picsum.photos/640/480/?image=1035",
                            Price = 0.2380325851168440m,
                            Title = "Rue"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 10,
                            Description = "Consultant",
                            ImageUrl = "https://picsum.photos/640/480/?image=1057",
                            Price = 0.7824904000066360m,
                            Title = "Gambia"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 13,
                            Description = "engage withdrawal strategy",
                            ImageUrl = "https://picsum.photos/640/480/?image=494",
                            Price = 0.821710189155280m,
                            Title = "Investment Account"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 14,
                            Description = "Checking Account Bedfordshire Corporate",
                            ImageUrl = "https://picsum.photos/640/480/?image=584",
                            Price = 0.4139317930806120m,
                            Title = "Markets"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 20,
                            Description = "Panama",
                            ImageUrl = "https://picsum.photos/640/480/?image=572",
                            Price = 0.3452683920036540m,
                            Title = "Metal"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 9,
                            Description = "Concrete online",
                            ImageUrl = "https://picsum.photos/640/480/?image=279",
                            Price = 0.1060484223505710m,
                            Title = "deposit"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 17,
                            Description = "Honduras Fresh",
                            ImageUrl = "https://picsum.photos/640/480/?image=58",
                            Price = 0.1551414543759080m,
                            Title = "lavender"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 6,
                            Description = "Tasty Handcrafted",
                            ImageUrl = "https://picsum.photos/640/480/?image=543",
                            Price = 0.3936420937995010m,
                            Title = "Branch"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 20,
                            Description = "Functionality Avon Tunnel",
                            ImageUrl = "https://picsum.photos/640/480/?image=316",
                            Price = 0.1475286628930210m,
                            Title = "cultivate"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 6,
                            Description = "Fantastic generating transmitting",
                            ImageUrl = "https://picsum.photos/640/480/?image=513",
                            Price = 0.2549104876870490m,
                            Title = "Row"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 7,
                            Description = "transmitter",
                            ImageUrl = "https://picsum.photos/640/480/?image=1070",
                            Price = 0.02090494771643890m,
                            Title = "copy"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 11,
                            Description = "Checking Account pink Extension",
                            ImageUrl = "https://picsum.photos/640/480/?image=390",
                            Price = 0.6227306632829190m,
                            Title = "Incredible"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 18,
                            Description = "Borders North Dakota Lead",
                            ImageUrl = "https://picsum.photos/640/480/?image=285",
                            Price = 0.598356417594230m,
                            Title = "Sleek Metal Sausages"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 20,
                            Description = "Personal Loan Account sky blue",
                            ImageUrl = "https://picsum.photos/640/480/?image=491",
                            Price = 0.3948621926085550m,
                            Title = "Health, Kids & Computers"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 11,
                            Description = "Games & Grocery",
                            ImageUrl = "https://picsum.photos/640/480/?image=226",
                            Price = 0.1010828707014020m,
                            Title = "Money Market Account"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 19,
                            Description = "Concrete hacking engineer",
                            ImageUrl = "https://picsum.photos/640/480/?image=309",
                            Price = 0.7273002993756330m,
                            Title = "card"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 18,
                            Description = "Norwegian Krone Mexico whiteboard",
                            ImageUrl = "https://picsum.photos/640/480/?image=553",
                            Price = 0.8898772856576140m,
                            Title = "embrace"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 10,
                            Description = "Internal compressing",
                            ImageUrl = "https://picsum.photos/640/480/?image=657",
                            Price = 0.7729354774012020m,
                            Title = "Tools, Clothing & Movies"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 16,
                            Description = "benchmark Baby & Music indexing",
                            ImageUrl = "https://picsum.photos/640/480/?image=450",
                            Price = 0.7864916241967240m,
                            Title = "Rubber"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 20,
                            Description = "Credit Card Account Cambridgeshire Gorgeous Steel Keyboard",
                            ImageUrl = "https://picsum.photos/640/480/?image=250",
                            Price = 0.4587265483488760m,
                            Title = "analyzing"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 1,
                            Description = "Licensed Concrete Table invoice",
                            ImageUrl = "https://picsum.photos/640/480/?image=954",
                            Price = 0.2662229721384780m,
                            Title = "Orchestrator"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 16,
                            Description = "Gorgeous Movies, Tools & Toys Unbranded",
                            ImageUrl = "https://picsum.photos/640/480/?image=157",
                            Price = 0.5458228812461210m,
                            Title = "global"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 16,
                            Description = "whiteboard",
                            ImageUrl = "https://picsum.photos/640/480/?image=303",
                            Price = 0.6680056450944130m,
                            Title = "Credit Card Account"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 20,
                            Description = "PNG Producer",
                            ImageUrl = "https://picsum.photos/640/480/?image=205",
                            Price = 0.2974991618137510m,
                            Title = "bluetooth"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 5,
                            Description = "generating Operative",
                            ImageUrl = "https://picsum.photos/640/480/?image=715",
                            Price = 0.08675315171696020m,
                            Title = "International"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 20,
                            Description = "Credit Card Account Fantastic Wooden Table",
                            ImageUrl = "https://picsum.photos/640/480/?image=523",
                            Price = 0.1559110218606340m,
                            Title = "Adaptive"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 11,
                            Description = "Planner optimizing Stand-alone",
                            ImageUrl = "https://picsum.photos/640/480/?image=185",
                            Price = 0.9493295582932270m,
                            Title = "orchid"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 10,
                            Description = "program Burg methodologies",
                            ImageUrl = "https://picsum.photos/640/480/?image=735",
                            Price = 0.4566694491096520m,
                            Title = "supply-chains"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 19,
                            Description = "Stream Bedfordshire payment",
                            ImageUrl = "https://picsum.photos/640/480/?image=445",
                            Price = 0.7047977895017360m,
                            Title = "Bermudian Dollar (customarily known as Bermuda Dollar)"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 16,
                            Description = "Direct",
                            ImageUrl = "https://picsum.photos/640/480/?image=569",
                            Price = 0.9712129756175320m,
                            Title = "transmitting"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 4,
                            Description = "Implementation",
                            ImageUrl = "https://picsum.photos/640/480/?image=869",
                            Price = 0.6174321635733850m,
                            Title = "Practical Metal Computer"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 20,
                            Description = "Awesome",
                            ImageUrl = "https://picsum.photos/640/480/?image=730",
                            Price = 0.601513794118140m,
                            Title = "coherent"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 14,
                            Description = "Utah Checking Account",
                            ImageUrl = "https://picsum.photos/640/480/?image=267",
                            Price = 0.4467689327813890m,
                            Title = "scalable"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 9,
                            Description = "integrate",
                            ImageUrl = "https://picsum.photos/640/480/?image=616",
                            Price = 0.661870311223840m,
                            Title = "pink"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 12,
                            Description = "synthesizing payment",
                            ImageUrl = "https://picsum.photos/640/480/?image=243",
                            Price = 0.7803640342306910m,
                            Title = "generating"
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 8,
                            Description = "application Wooden Garden & Tools",
                            ImageUrl = "https://picsum.photos/640/480/?image=283",
                            Price = 0.3053544692138260m,
                            Title = "Branch"
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 16,
                            Description = "generating bypass",
                            ImageUrl = "https://picsum.photos/640/480/?image=338",
                            Price = 0.53117129098640m,
                            Title = "back up"
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 14,
                            Description = "Grocery, Clothing & Tools COM Buckinghamshire",
                            ImageUrl = "https://picsum.photos/640/480/?image=966",
                            Price = 0.9556480531557240m,
                            Title = "Cotton"
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 13,
                            Description = "Bahrain EXE compressing",
                            ImageUrl = "https://picsum.photos/640/480/?image=973",
                            Price = 0.4160300266222160m,
                            Title = "Principal"
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 17,
                            Description = "Wooden generate",
                            ImageUrl = "https://picsum.photos/640/480/?image=528",
                            Price = 0.2624035703168950m,
                            Title = "Personal Loan Account"
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 8,
                            Description = "Handcrafted Plastic Chicken programming Intelligent Metal Pizza",
                            ImageUrl = "https://picsum.photos/640/480/?image=476",
                            Price = 0.6902883835055780m,
                            Title = "Investor"
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 2,
                            Description = "Well Refined",
                            ImageUrl = "https://picsum.photos/640/480/?image=506",
                            Price = 0.8466194038976610m,
                            Title = "navigate"
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 10,
                            Description = "platforms visionary",
                            ImageUrl = "https://picsum.photos/640/480/?image=75",
                            Price = 0.07624610507263540m,
                            Title = "pixel"
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 4,
                            Description = "web-readiness algorithm",
                            ImageUrl = "https://picsum.photos/640/480/?image=14",
                            Price = 0.8455001813167130m,
                            Title = "Unbranded Soft Table"
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 18,
                            Description = "architect Corporate",
                            ImageUrl = "https://picsum.photos/640/480/?image=719",
                            Price = 0.1061750432166690m,
                            Title = "Auto Loan Account"
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 11,
                            Description = "PCI Rustic Cambodia",
                            ImageUrl = "https://picsum.photos/640/480/?image=810",
                            Price = 0.4733940649484770m,
                            Title = "Small Granite Shoes"
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 17,
                            Description = "Incredible Concrete Chips New Mexico Program",
                            ImageUrl = "https://picsum.photos/640/480/?image=332",
                            Price = 0.9295558665974310m,
                            Title = "Sleek Granite Towels"
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 1,
                            Description = "reinvent Som back up",
                            ImageUrl = "https://picsum.photos/640/480/?image=205",
                            Price = 0.2894745414195920m,
                            Title = "Bedfordshire"
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 5,
                            Description = "Rustic Metal Mouse",
                            ImageUrl = "https://picsum.photos/640/480/?image=549",
                            Price = 0.5180219383014810m,
                            Title = "Assistant"
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 11,
                            Description = "online",
                            ImageUrl = "https://picsum.photos/640/480/?image=638",
                            Price = 0.3754106238206730m,
                            Title = "turquoise"
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 7,
                            Description = "benchmark",
                            ImageUrl = "https://picsum.photos/640/480/?image=854",
                            Price = 0.327662940172660m,
                            Title = "Generic Metal Chair"
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 12,
                            Description = "Awesome Concrete Cheese Handmade revolutionize",
                            ImageUrl = "https://picsum.photos/640/480/?image=93",
                            Price = 0.7786348482765020m,
                            Title = "Berkshire"
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 1,
                            Description = "Configurable",
                            ImageUrl = "https://picsum.photos/640/480/?image=334",
                            Price = 0.707163935200380m,
                            Title = "Awesome Granite Fish"
                        });
                });

            modelBuilder.Entity("MarketApp.Shared.Product", b =>
                {
                    b.HasOne("MarketApp.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
